source 'https://rubygems.org'

ruby '3.2.2'

# Web framework
gem 'rails', '~> 7.0.8'
gem 'puma', '~> 6.3'

# Database
gem 'pg', '~> 1.5'  # PostgreSQL adapter
gem 'redis', '~> 5.0'  # Redis client

# Authentication & Authorization
gem 'devise', '~> 4.9'
gem 'pundit', '~> 2.3'

# API
gem 'jbuilder', '~> 2.11'

# Background Jobs
gem 'sidekiq', '~> 7.1'

# Monitoring
gem 'prometheus-client', '~> 4.0'

# Utilities
gem 'dotenv-rails', '~> 2.8'

group :development, :test do
  gem 'rspec-rails', '~> 6.0'
  gem 'factory_bot_rails', '~> 6.2'
  gem 'faker', '~> 3.2'
  gem 'debug', '~> 1.8'
end

group :development do
  gem 'web-console', '~> 4.2'
  gem 'rubocop', '~> 1.56'
  gem 'annotate', '~> 3.2'
end

group :test do
  gem 'capybara', '~> 3.39'
  gem 'selenium-webdriver', '~> 4.12'
  gem 'webmock', '~> 3.19'
  gem 'vcr', '~> 6.2'
end